blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/Veridian-Zenith/Voix/discussions/new
    about: Please ask and answer questions here.
  - name: Security Vulnerability
    url: https://github.com/Veridian-Zenith/Voix/security/policy
    about: Please report security vulnerabilities here.
