.TH VOIX 1 "March 2026" "Voix 2.3.2" "User Commands"
.SH NAME
voix \- privilege escalation tool for the Keeper of Realms
.SH SYNOPSIS
.B voix
[\fIOPTIONS\fR]
[\fIINCANTATION\fR [\fIARGS\fR...]]
.SH DESCRIPTION
Voix is a modern, secure, and easy-to-use privilege escalation tool.
It provides a flexible rule-based system for granting permissions (Ordinations) and uses PAM for authentication.
.SH OPTIONS
.TP
.B \-u, \-\-user \fIUSER\fR
Execute incantation as the specified user (default: root).
.TP
.B \-C, \-\-clear
Clear any persisted authentications for the current user.
.TP
.B \-n, \-\-non-interactive
Fail if a password is required, rather than prompting.
.SH CONFIGURATION
The Voix configuration file, located at \fI/etc/voix.conf\fR, defines the rules for command execution.
.PP
The syntax is as follows:
.PP
.B [ordain|shun] [trust] <ident> [mask <target>] [rite <command> [args ...]]
.PP
.TP
.B ordain
Allow the user can execute a command.
.TP
.B shun
Prevent the user from executing any command.
.TP
.B trust
The user will not be prompted for a password.
.TP
.B mask
The user to execute the command as (defaults to root).
.TP
.B rite
The command to be executed. If no command is specified, any command is allowed.
.SH AUTHENTICATION
Voix uses the Pluggable Authentication Modules (PAM) framework for authentication.
The service name is \fBvoix\fR, and its configuration can be found in \fI/etc/pam.d/voix\fR.
.SH EXAMPLES
Execute \fBwhoami\fR as root:
.IP
voix whoami
.PP
Execute \fBwhoami\fR as a mask user:
.IP
voix -u user whoami
.PP
Start a shell as root:
.IP
voix -s
.SH ARCHITECT
Veridian-Zenith 2026 (Dae Euhwa - daedaevibin@ik.me)
.SH SEE ALSO
.BR sudo (8),
.BR doas (1),
.BR pam (8)
