name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master, develop ]

env:
  BUILD_TYPE: Release

jobs:
  # Build and test on multiple platforms
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-22.04]
        compiler: [gcc, clang]
        exclude:
          - os: ubuntu-20.04
            compiler: clang

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpam0g-dev \
          liblua5.3-dev \
          pkg-config \
          cmake \
          clang \
          polkitd \
          libpolkit-agent-1-dev \
          libpolkit-gobject-1-dev \
          libgio-2.0-dev

    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build project
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ./voixcheck ../src/voix.conf.sample

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: voix-${{ matrix.os }}-${{ matrix.compiler }}
        path: build/

  # Security scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run security checks
      run: |
        # Basic static analysis
        find src -name "*.cpp" -o -name "*.hpp" | xargs -I {} sh -c 'echo "Checking {}"; grep -n "strcpy\|strcat\|sprintf" {} || true'

        # Check for setuid usage
        grep -r "setuid\|seteuid" src/ || echo "No setuid calls found"

  # Release job
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, security]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/voix-*/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # AUR package update (if this becomes an AUR package again)
  aur-update:
    name: Update AUR Package
    runs-on: ubuntu-latest
    needs: [build, security]
    if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'Veridian-Zenith/Voix'

    steps:
    - name: Checkout AUR repository
      run: |
        git clone https://aur.archlinux.org/voix.git aur-repo
        cd aur-repo
        # Update PKGBUILD with new version
        sed -i "s/pkgver=.*/pkgver=${GITHUB_REF_NAME#v}/" PKGBUILD
        sed -i "s/pkgrel=.*/pkgrel=1/" PKGBUILD
